"use client";

import { useMemo, useState } from "react";
import { Copy, FileDown, History, Plus, ReceiptText, Save, Snowflake, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { downloadQuotePdf, QuoteDocument, QuoteItem } from "@/lib/quote-pdf";

const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const uid = () => crypto.randomUUID();
const today = new Date().toISOString().slice(0, 10);
type StoredQuote = { id: string; customer_name: string; total: number; created_at: string; payload: { quote?: QuoteDocument } };

function freshQuote(): QuoteDocument {
  return {
    number: `CO-${new Date().getFullYear()}-${String(Date.now()).slice(-5)}`, issueDate: today,
    validUntil: new Date(Date.now() + 7 * 86400000).toISOString().slice(0, 10),
    customer: { name: "", document: "", phone: "", email: "", address: "" },
    provider: { name: "Clima Serviços", document: "", phone: "", email: "" },
    serviceType: "Instalação de ar-condicionado", equipment: "Split Hi-Wall",
    items: [{ id: uid(), description: "Instalação de ar-condicionado split até 12.000 BTU/h", quantity: 1, unit: "un", unitPrice: 900 }, { id: uid(), description: "Kit de materiais para instalação até 3 metros", quantity: 1, unit: "kit", unitPrice: 350 }],
    paymentTerms: "50% na aprovação e 50% após a conclusão do serviço.",
    executionTerms: "Agendamento em até 5 dias úteis após a aprovação, sujeito à disponibilidade.",
    included: "Tubulação de cobre e isolamento térmico até 3 metros\nCabo de interligação entre as unidades até 3 metros\nSuporte para a unidade externa\nMangueira de dreno até 3 metros\nFixação, vácuo, testes e orientação de uso",
    exclusions: "Ponto elétrico, disjuntor e adequações na rede elétrica\nCortes, rasgos, pintura, gesso, marcenaria ou acabamento civil\nAndaimes, plataformas ou acesso especial\nDesinstalação e descarte de equipamento existente\nServiços ou materiais além dos limites descritos nos itens",
    notes: "Valores consideram acesso livre e condições normais de instalação. Qualquer serviço adicional será informado e aprovado antes da execução.",
  };
}

export default function Home() {
  const [quote, setQuote] = useState(freshQuote); const [status, setStatus] = useState(""); const [saving, setSaving] = useState(false);
  const [view, setView] = useState<"edit" | "history">("edit"); const [history, setHistory] = useState<StoredQuote[]>([]); const [selected, setSelected] = useState<StoredQuote | null>(null);
  const total = useMemo(() => quote.items.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0), [quote.items]);
  const update = <K extends keyof QuoteDocument>(key: K, value: QuoteDocument[K]) => setQuote((current) => ({ ...current, [key]: value }));
  const updateParty = (party: "customer" | "provider", key: string, value: string) => setQuote((current) => ({ ...current, [party]: { ...current[party], [key]: value } }));
  const updateItem = (id: string, patch: Partial<QuoteItem>) => update("items", quote.items.map((item) => item.id === id ? { ...item, ...patch } : item));
  const validate = () => !quote.customer.name.trim() ? "Informe o nome do cliente." : quote.items.some((item) => !item.description.trim() || item.quantity <= 0) || !quote.items.length ? "Revise os itens e suas quantidades." : "";
  async function loadHistory() { const data = await fetch("/api/quotes").then((response) => response.json()) as { quotes?: StoredQuote[] }; setHistory(data.quotes ?? []); }
  async function openHistory() { setSelected(null); setView("history"); setStatus(""); try { await loadHistory(); } catch { setStatus("Não foi possível carregar o histórico."); } }
  async function saveQuote(event: { preventDefault(): void }) {
    event.preventDefault(); const error = validate(); if (error) { setStatus(error); return; }
    setSaving(true); setStatus(""); downloadQuotePdf(quote);
    try { const response = await fetch("/api/quotes", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ customer: quote.customer.name, type: "installation", total, quote }) }); if (!response.ok) throw new Error(); await loadHistory(); setView("history"); setStatus("Orçamento salvo no histórico e PDF baixado com sucesso."); }
    catch { setStatus("O PDF foi baixado, mas não foi possível salvar no histórico agora."); } finally { setSaving(false); }
  }
  function exportPdf() { const error = validate(); if (error) return setStatus(error); downloadQuotePdf(quote); setStatus("PDF profissional gerado com sucesso."); }
  function duplicate(stored: StoredQuote) { const source = stored.payload.quote; if (!source) return; setQuote({ ...source, number: `CO-${new Date().getFullYear()}-${String(Date.now()).slice(-5)}`, items: source.items.map((item) => ({ ...item, id: uid() })) }); setSelected(null); setView("edit"); setStatus("Cópia criada. Revise os dados antes de salvar."); }

  return <main className="min-h-screen bg-background pb-28 text-foreground">
    <header className="sticky top-0 z-20 border-b bg-background/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-3xl items-center justify-between px-4"><div className="flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Snowflake className="h-5 w-5" /></span><div><p className="text-sm font-black">Clima Orçamentos</p><p className="text-[11px] text-muted-foreground">Propostas profissionais no celular</p></div></div><Button type="button" variant="ghost" size="sm" onClick={view === "edit" ? openHistory : () => { setSelected(null); setView("edit"); }}>{view === "edit" ? <><History /> Histórico</> : <><Plus /> Novo</>}</Button></div></header>
    {view === "history" ? <HistoryView quotes={history} selected={selected} status={status} onSelect={setSelected} onClose={() => setSelected(null)} onDownload={(stored) => stored.payload.quote && downloadQuotePdf(stored.payload.quote)} onDuplicate={duplicate} /> :
    <form onSubmit={saveQuote} className="mx-auto max-w-3xl space-y-5 px-4 py-5">
      <section className="hero-card"><div><p className="eyebrow">Nova proposta comercial</p><h1>{money.format(total)}</h1><p>Ao salvar, o orçamento entra no histórico e o PDF é baixado.</p></div><ReceiptText className="h-9 w-9 text-cyan-200" /></section>
      <Section step="1" title="Identificação" subtitle="Número, datas e dados de quem presta o serviço"><Grid><Field label="Número da proposta"><Input value={quote.number} onChange={(e) => update("number", e.target.value)} /></Field><Field label="Data de emissão"><Input type="date" value={quote.issueDate} onChange={(e) => update("issueDate", e.target.value)} /></Field><Field label="Válida até"><Input type="date" value={quote.validUntil} onChange={(e) => update("validUntil", e.target.value)} /></Field><Field label="Empresa / profissional"><Input value={quote.provider.name} onChange={(e) => updateParty("provider", "name", e.target.value)} /></Field><Field label="CPF / CNPJ"><Input value={quote.provider.document} onChange={(e) => updateParty("provider", "document", e.target.value)} /></Field><Field label="Telefone"><Input value={quote.provider.phone} onChange={(e) => updateParty("provider", "phone", e.target.value)} /></Field><Field label="E-mail"><Input value={quote.provider.email} onChange={(e) => updateParty("provider", "email", e.target.value)} /></Field></Grid></Section>
      <Section step="2" title="Cliente e local" subtitle="Dados exibidos no cabeçalho do orçamento"><Grid><Field label="Nome do cliente"><Input value={quote.customer.name} onChange={(e) => updateParty("customer", "name", e.target.value)} /></Field><Field label="CPF / CNPJ"><Input value={quote.customer.document} onChange={(e) => updateParty("customer", "document", e.target.value)} /></Field><Field label="WhatsApp"><Input value={quote.customer.phone} onChange={(e) => updateParty("customer", "phone", e.target.value)} /></Field><Field label="E-mail"><Input value={quote.customer.email} onChange={(e) => updateParty("customer", "email", e.target.value)} /></Field><Field label="Endereço do serviço" wide><Input value={quote.customer.address} onChange={(e) => updateParty("customer", "address", e.target.value)} /></Field></Grid></Section>
      <Section step="3" title="Escopo e itens" subtitle="Quantidades, valores unitários e subtotais"><Grid><Field label="Tipo de serviço"><Input value={quote.serviceType} onChange={(e) => update("serviceType", e.target.value)} /></Field><Field label="Equipamento"><Input value={quote.equipment} onChange={(e) => update("equipment", e.target.value)} /></Field></Grid><div className="mt-4 space-y-3">{quote.items.map((item, index) => <article className="item-card" key={item.id}><div className="item-title"><strong>Item {index + 1}</strong><Button type="button" variant="ghost" size="icon-sm" onClick={() => update("items", quote.items.filter((entry) => entry.id !== item.id))}><Trash2 /></Button></div><Field label="Descrição"><Input value={item.description} onChange={(e) => updateItem(item.id, { description: e.target.value })} /></Field><div className="item-values"><Field label="Quantidade"><Input type="number" min="0.01" step="0.01" value={item.quantity} onChange={(e) => updateItem(item.id, { quantity: Number(e.target.value) })} /></Field><Field label="Unidade"><Input value={item.unit} onChange={(e) => updateItem(item.id, { unit: e.target.value })} /></Field><Field label="Valor unitário"><Input type="number" min="0" step="0.01" value={item.unitPrice} onChange={(e) => updateItem(item.id, { unitPrice: Number(e.target.value) })} /></Field></div><p className="item-subtotal">Subtotal <strong>{money.format(item.quantity * item.unitPrice)}</strong></p></article>)}</div><Button type="button" variant="outline" className="mt-3 w-full" onClick={() => update("items", [...quote.items, { id: uid(), description: "", quantity: 1, unit: "un", unitPrice: 0 }])}><Plus /> Adicionar item</Button></Section>
      <Section step="4" title="Condições comerciais" subtitle="Pagamento, execução e observações"><Stack><Field label="Condições de pagamento"><Textarea value={quote.paymentTerms} onChange={(e) => update("paymentTerms", e.target.value)} /></Field><Field label="Prazo e condições de execução"><Textarea value={quote.executionTerms} onChange={(e) => update("executionTerms", e.target.value)} /></Field><Field label="Observações"><Textarea value={quote.notes} onChange={(e) => update("notes", e.target.value)} /></Field></Stack></Section>
      <Section step="5" title="Escopo detalhado" subtitle="Use uma linha para cada item"><Stack><Field label="Itens inclusos"><Textarea className="min-h-40" value={quote.included} onChange={(e) => update("included", e.target.value)} /></Field><Field label="Não inclusos / exclusões"><Textarea className="min-h-40" value={quote.exclusions} onChange={(e) => update("exclusions", e.target.value)} /></Field></Stack></Section>
      {status && <p className={`status ${status.includes("sucesso") || status.includes("criada") ? "status-ok" : "status-warn"}`}>{status}</p>}
      <footer className="action-bar"><div className="mx-auto flex max-w-3xl items-center gap-3"><div className="min-w-0 flex-1"><p>Total da proposta</p><strong>{money.format(total)}</strong></div><Button type="button" onClick={exportPdf} variant="outline" className="h-12 rounded-2xl"><FileDown /><span className="hidden sm:inline">Só PDF</span></Button><Button type="submit" disabled={saving} className="h-12 rounded-2xl px-5 font-bold"><Save />{saving ? "Salvando..." : "Salvar + PDF"}</Button></div></footer>
    </form>}
  </main>;
}

function Section({ step, title, subtitle, children }: { step: string; title: string; subtitle: string; children: React.ReactNode }) { return <section className="card-section"><div className="section-heading"><span className="step">{step}</span><div><h2>{title}</h2><p>{subtitle}</p></div></div>{children}</section>; }
function Field({ label, wide, children }: { label: string; wide?: boolean; children: React.ReactNode }) { return <label className={`field-label ${wide ? "sm:col-span-2" : ""}`}><span>{label}</span>{children}</label>; }
function Grid({ children }: { children: React.ReactNode }) { return <div className="form-grid">{children}</div>; }
function Stack({ children }: { children: React.ReactNode }) { return <div className="space-y-4">{children}</div>; }

function HistoryView({ quotes, selected, status, onSelect, onClose, onDownload, onDuplicate }: { quotes: StoredQuote[]; selected: StoredQuote | null; status: string; onSelect: (quote: StoredQuote) => void; onClose: () => void; onDownload: (quote: StoredQuote) => void; onDuplicate: (quote: StoredQuote) => void }) {
  if (selected) return <QuoteDetails stored={selected} onClose={onClose} onDownload={onDownload} onDuplicate={onDuplicate} />;
  return <section className="mx-auto max-w-3xl space-y-4 px-4 py-5"><div><h1 className="text-2xl font-black">Orçamentos salvos</h1><p className="text-sm text-muted-foreground">Toque em um registro para consultar todos os dados.</p></div>{status && <p className="status status-ok">{status}</p>}{quotes.length === 0 ? <div className="card-section py-12 text-center"><History className="mx-auto mb-3 text-muted-foreground" /><p className="font-bold">Nenhum orçamento salvo</p></div> : quotes.map((stored) => <button type="button" key={stored.id} onClick={() => onSelect(stored)} className="history-card"><div><strong>{stored.customer_name}</strong><span>{stored.payload.quote?.number ?? "Registro antigo"} · {new Date(stored.created_at).toLocaleDateString("pt-BR")}</span></div><b>{money.format(stored.total)}</b></button>)}</section>;
}

function QuoteDetails({ stored, onClose, onDownload, onDuplicate }: { stored: StoredQuote; onClose: () => void; onDownload: (quote: StoredQuote) => void; onDuplicate: (quote: StoredQuote) => void }) {
  const detail = stored.payload.quote; if (!detail) return <section className="mx-auto max-w-3xl px-4 py-5"><Button onClick={onClose}>Voltar</Button><p className="mt-4">Este registro antigo não possui dados detalhados.</p></section>;
  const total = detail.items.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0);
  return <section className="mx-auto max-w-3xl space-y-4 px-4 py-5"><div className="flex items-start justify-between"><div><p className="eyebrow text-primary">Detalhes do orçamento</p><h1 className="text-2xl font-black">{detail.customer.name}</h1><p className="text-sm text-muted-foreground">{detail.number} · {detail.issueDate}</p></div><Button variant="ghost" size="icon" onClick={onClose}><X /></Button></div><div className="detail-total"><span>Valor total</span><strong>{money.format(total)}</strong></div><Detail label="Cliente" value={[detail.customer.document, detail.customer.phone, detail.customer.email, detail.customer.address].filter(Boolean).join(" · ")} /><Detail label="Serviço" value={`${detail.serviceType} · ${detail.equipment}`} /><section className="card-section"><h2 className="mb-3 font-black">Itens</h2>{detail.items.map((item) => <div key={item.id} className="detail-item"><div><strong>{item.description}</strong><span>{item.quantity} {item.unit} × {money.format(item.unitPrice)}</span></div><b>{money.format(item.quantity * item.unitPrice)}</b></div>)}</section><Detail label="Pagamento" value={detail.paymentTerms} /><Detail label="Prazo / execução" value={detail.executionTerms} /><Detail label="Itens inclusos" value={detail.included} pre /><Detail label="Não inclusos / exclusões" value={detail.exclusions} pre /><Detail label="Observações" value={detail.notes} /><div className="grid gap-3 sm:grid-cols-2"><Button className="h-12 rounded-2xl" onClick={() => onDownload(stored)}><FileDown /> Baixar PDF novamente</Button><Button variant="outline" className="h-12 rounded-2xl" onClick={() => onDuplicate(stored)}><Copy /> Duplicar e editar</Button></div></section>;
}
function Detail({ label, value, pre }: { label: string; value: string; pre?: boolean }) { return <section className="card-section"><h2 className="text-xs font-black uppercase tracking-wider text-primary">{label}</h2><p className={`mt-2 text-sm ${pre ? "whitespace-pre-line" : ""}`}>{value || "Não informado"}</p></section>; }
